service: serverless-tfjs-app

provider:
  name: aws
  runtime: nodejs16.x
  #memorySize: 3008
  timeout: 900
  stage: dev
  region: ap-northeast-2  #서울 리전
  # environment:
    #AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  ecr:
    images:
      slsdln:
        path: './'
        platform : 'linux/amd64'

functions:
  dln:
    memorySize: 10240 # 메모리 할당량을 증가시킵니다 (예: 1024 MB)
    url : true
    image:
      name: slsdln
      command:
        - app.handler
    # events:
    #   - http:
    #       path: /
    #       method: ANY
    #       cors: true
    #   - http:
    #       path: /{proxy+}
    #       method: ANY
    #       cors: true