service: serverless-tfjs-app

provider:
  name: aws
  runtime: nodejs16.x
  #memorySize: 3008
  #timeout: 10
  stage: dev
  region: ap-northeast-2  #서울 리전
  # environment:
    #AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  ecr:
    images:
      slsdln:
        path: './'
        platform : 'linux/amd64'

functions:
  app:
    image:
      name: slsdln
      command:
        - app.handler
    events:
      - http:
          path: /
          method: ANYx
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true
    mimeTypes:
      - 'multipart/form-data'
